Vagrant.configure("2") do |config|
    config.vagrant.plugins = "vagrant-libvirt"
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
    config.vm.define "pbsrocky8" do |node|
      node.vm.box = "generic/rocky8"
      node.vm.hostname = "pbsrocky8"
      node.vm.network "private_network", ip: "10.10.11.10"
      node.vm.provider :libvirt do |lv|
        lv.storage_pool_name="pool"
        lv.memory = "8196"
        lv.cpus = "8"
      end
    end

    config.vm.define "pbsubuntu22" do |node|
      node.vm.box = "generic/ubuntu2204"
      node.vm.hostname = "pbsubuntu22"
      node.vm.network "private_network", ip: "10.10.11.11"
      node.vm.provider :libvirt do |lv|
        lv.storage_pool_name="pool"
        lv.memory = "8196"
        lv.cpus = "8"
      end
      node.vm.provision "ansible" do |ansible|
      ansible.limit = "all"
      ansible.playbook = "install_pbs.yml"
      end
    end
end
