- name: Create the slurm directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ SLURMD_OWNER }}"
    group: "{{ SLURMD_OWNER_GRP }}"
    mode:  "{{ item.perm }}"
  with_items:
    - {path: "/var/spool/slurmd", perm: "0755"}

- name: Allow slurmd port
  ufw:
    rule: allow
    port: '6818'
    proto: tcp

- name: Setup systemd service
  template:
    src: slurmd.service.j2
    dest: /etc/systemd/system/slurmd.service

- name: Restart slurmd
  systemd:
    daemon_reload: true
    name: slurmd
    state: restarted
    enabled: yes

